[project]
name = "vsdlm"
version = "1.0.0"
description = "Visual only speech detection by lip movement."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mediapipe==0.10.21",
    "numpy==1.26.4",
    "pandas==2.3.3",
]
